### ISSUE TITLE
Create active state for buttons, etc to differentiate from hover

### ISSUE THREAD

**Issue by gianpaj** [Pixelkit/PixelKit-Bootstrap-UI-Kits#5]
Basically clickable elements should have become darker when clicked.

For example Bootstrap 3:

``` css
.btn:active, .btn.active {
  background-image: none;
  outline: 0;
  -webkit-box-shadow: inset 0 3px 5px rgba(0,0,0,0.125);
  box-shadow: inset 0 3px 5px rgba(0,0,0,0.125);
}
```
